---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ppkorma1/sasama
    - /usr/local/bin/composer install --no-dev --optimize-autoloader --ignore-platform-req=ext-fileinfo --quiet --working-dir=$DEPLOYPATH
    - $DEPLOYPATH/artisan migrate --force
    - $DEPLOYPATH/artisan config:cache
    - $DEPLOYPATH/artisan view:cache
    - rm -f $HOME/public_html/hot
